# Where things are
source:          .
destination:     _site
plugins_dir:     _plugins
layouts_dir:     _layouts
data_dir:        _data
includes_dir:    _includes

# Reading Files
safe:                 false
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
  - /docs # ignore Minimal Mistakes /docs
  - /test # ignore Minimal Mistakes /test
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
strict_front_matter: false

# Outputting
liquid:
  error_mode: warn

# Base Metadata
title                    : "Charlies Nicholson"
title_separator          : "-"
name                     : "Charlie Nicholson"
description              : "Gund Graduate Fellow, PhD, Rubenstein School of Environment and Natural Resources"
url                      : "https://ccnicholson.github.io"

# Site Author
author:
  name             : "Charlie Nicholson"
  avatar           : "/assets/images/avatar.png"
  bio              : "Gund Graduate Fellow, PhD, Rubenstein School of Environment and Natural Resources"
  location         : Gund Institute for Environment, University of Vermont, 617 Main St. Burlington, VT, USA 05405
  email            : ccnichol@uvm.edu
  github           : https://github.com/CCNicholson
  google_scholar   : https://scholar.google.se/citations?user=WDVOmakAAAAJ&hl=en
  twitter          : https://twitter.com/buzznicholson

# Sass/SCSS
sass:
  sass_dir: _sass
  style: expanded

# Serving
detach:  false
port:    4000
host:    127.0.0.1
baseurl: ""
show_dir_listing: false

gems:
  - jekyll-babel